name: Python wheels
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main


jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        os: [windows-latest]
        # arch: [x86_64, aarch64]
        #arch: [x86_64, arm64]
        arch: [x86_64]
        exclude:
          - os: windows-latest
            arch: aarch64
          - os: macos-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v2

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-build.txt

      # This step is run when tagging (typically a release)
      # Build all wheels
      - name: Sets env vars for tagging
        run: |
          echo "CIBW_BUILD=cp39-* cp310-* cp311-* cp312-*" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags') == true

      # This step is run when not tagging (typically a PR)
      # Build just one wheel
      - name: Sets env vars when not tagging
        run: |
          echo "CIBW_BUILD=cp312-*" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags') != true

      - name: Build wheels (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: 'cp312-win_amd64'
          #CIBW_BUILD: 'cp310-win32'
          CIBW_BEFORE_BUILD: bash prebuild.sh
          CIBW_SKIP: ${{ env.CIBW_SKIP}}'
          # Skip 32-bit builds
          #CIBW_SKIP: "*-win32" ${{ env.CIBW_SKIP}}'
          CIBW_TEST_REQUIRES: pytest blosc2
          CIBW_TEST_COMMAND: >
            set BTUNE_TRACE=1 &&
            set BTUNE_MODELS_DIR={project}/examples/models &&
            cd {project}/examples &&
            python btune_config.py
          CIBW_BUILD_VERBOSITY: 1

      - name: Build wheels (Linux / Mac OSX)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: CMAKE_OSX_ARCHITECTURES=x86_64 bash prebuild.sh
          CIBW_SKIP: '*-manylinux*_i686 *-musllinux_* ${{ env.CIBW_SKIP}}'
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_TEST_REQUIRES: pytest blosc2
          # Test against the test suite in python-blosc2
          CIBW_TEST_COMMAND: BTUNE_MODELS_DIR={project}/examples/models BTUNE_BALANCE=.1 BLOSC_TRACE=1 BTUNE_TRACE=1 python -m pytest -s {project}/python-blosc2/tests
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS_MACOS: "x86_64"

      - name: Build wheels (Mac OSX arm64)
        if: runner.os != 'Windows' && runner.os != 'Linux'
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: CMAKE_OSX_ARCHITECTURES=arm64 bash prebuild.sh
          CIBW_SKIP: '*-manylinux*_i686 *-musllinux_* ${{ env.CIBW_SKIP}}'
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_TEST_REQUIRES: pytest blosc2
          # Test against the test suite in python-blosc2
          CIBW_TEST_COMMAND: BTUNE_MODELS_DIR={project}/examples/models BTUNE_BALANCE=.1 BLOSC_TRACE=1 BTUNE_TRACE=1 python -m pytest -s {project}/python-blosc2/tests
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS_MACOS: "arm64"

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl


  upload_pypi:
    needs: [ build_wheels ]  # last but not least
    runs-on: ubuntu-latest
    # Only upload wheels when tagging (typically a release)
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.blosc_pypi_secret }}
